// import {Meteor} from 'meteor/meteor';
// import {Buildings, Cleaners, Schedules} from '/lib/collections/index';
// import Seeder from 'dr-seeder';
// import {createJobs} from '../scheduleEditor';

// Meteor.startup(function() {
//
//   Seeder.seed('Buildings init', Buildings, {
//     data: [
//       {name: 'Letomostie 7', duration: 60, assigned: true},
//       {name: 'Letomostie 11', duration: 60, assigned: true},
//       {name: 'Letomostie 13', duration: 60, assigned: true},
//       {name: 'Letomostie 15', duration: 60, assigned: true},
//       {name: 'Novomestská 2', duration: 60, assigned: true},
//       {name: 'Novomestská 4', duration: 60, assigned: true},
//       {name: 'T.G.Masaryka 30', duration: 60, assigned: true},
//       {name: 'T.G.Masaryka 28', duration: 60, assigned: true},
//       {name: 'T.G.Masaryka 17', duration: 30, assigned: true},
//       {name: 'Podzámska 1', duration: 60, assigned: true},
//       {name: 'Podzámska 7', duration: 60, assigned: true},
//       {name: 'MAGNUM', duration: 150, assigned: true},
//       {name: 'T.G. Masaryka 14', duration: 60, assigned: true},
//       {name: 'T.G. Masaryka 16', duration: 60, assigned: true},
//       {name: 'T.G. Masaryka 18', duration: 60, assigned: true},
//       {name: 'SNP. 48', duration: 60, assigned: true},
//       {name: 'SNP. 50', duration: 60, assigned: true},
//       {name: 'SNP. 52', duration: 60, assigned: true},
//       {name: 'SNP. 54', duration: 60, assigned: true},
//       {name: 'Gymnastická hala', duration: 90, assigned: true},
//       {name: 'ABC klíma', duration: 60, assigned: true},
//       {name: 'G. Bethlena 57', duration: 60, assigned: true},
//       {name: 'Cyrilometódska 44', duration: 30, assigned: true},
//       {name: 'Cyrilometódska 46', duration: 30, assigned: true},
//       {name: 'Cyrilometódska 48', duration: 30, assigned: true},
//       {name: 'SNP 58', duration: 30, assigned: true},
//       {name: 'Šafáriková 26', duration: 30, assigned: true},
//       {name: 'Šafáriková 28', duration: 30, assigned: true},
//       {name: 'Šafáriková 22', duration: 60, assigned: true},
//       {name: 'Šafáriková 20', duration: 60, assigned: true},
//       {name: 'Šafáriková 2', duration: 30, assigned: true},
//       {name: 'Lastovičia 3', duration: 60, assigned: true},
//       {name: 'Lastovičia 1', duration: 60, assigned: true},
//       {name: 'Nábrežná 7', duration: 60, assigned: true},
//       {name: 'Nábrežná 9', duration: 60, assigned: true},
//       {name: 'Nábrežná 13', duration: 60, assigned: true},
//       {name: 'Andovská 21', duration: 60, assigned: true},
//       {name: 'Andovská 23', duration: 60, assigned: true},
//       {name: 'S.H. Vajanského 37', duration: 60, assigned: true},
//       {name: 'S.H. Vajanského 39', duration: 60, assigned: true},
//       {name: 'S.H. Vajanského 41', duration: 60, assigned: true},
//       {name: 'T. Vansovej 32', duration: 60, assigned: true},
//       {name: 'T. Vansovej 30', duration: 60, assigned: true},
//       {name: 'Komárňanska 59', duration: 150, assigned: true},
//       {name: 'Dom politických strán', duration: 60, assigned: true},
//       {name: 'Komárňanska 29', duration: 30, assigned: true},
//       {name: 'Komárňanska 27', duration: 30, assigned: true},
//       {name: 'Nábrežná 35', duration: 60, assigned: true},
//       {name: 'Nábrežná 37', duration: 60, assigned: true},
//       {name: 'Nábrežná 53', duration: 60, assigned: true},
//       {name: 'Nábrežná 55', duration: 60, assigned: true},
//       {name: 'S.H Vajanského 9', duration: 60, assigned: true},
//       {name: 'S.H Vajanského 17', duration: 60, assigned: true},
//       {name: 'Šoltésová 9', duration: 60, assigned: true},
//       {name: 'J.Krála 20', duration: 60, assigned: true},
//       {name: 'J.Krála 22', duration: 60, assigned: true},
//       {name: 'T. Vansovej 24', duration: 60, assigned: true},
//       {name: 'T. Vansovej 22', duration: 60, assigned: true},
//       {name: 'T. Vansovej 20', duration: 60, assigned: true},
//       {name: 'T. Vansovej 18', duration: 60, assigned: true},
//       {name: 'T. Vansovej 16', duration: 60, assigned: true},
//       {name: 'T. Vansovej 14', duration: 60, assigned: true},
//       {name: 'Gogoľova 1', duration: 30, assigned: true},
//       {name: 'Gogoľova 3', duration: 60, assigned: true},
//       {name: 'Gogoľova 5', duration: 60, assigned: true},
//       {name: 'Krasková 4', duration: 60, assigned: true},
//       {name: 'Holého 4', duration: 90, assigned: true},
//       {name: 'Hlboká 1', duration: 30, assigned: true},
//       {name: 'Gogoľová 2', duration: 60, assigned: true},
//       {name: 'Komárňanska 31', duration: 60, assigned: true},
//       {name: 'Ďorocká 3', duration: 60, assigned: true},
//       {name: 'Ďorocká 5', duration: 60, assigned: true},
//       {name: 'Ďorocká 7', duration: 60, assigned: true},
//       {name: 'T.G. Masaryka 32', duration: 60, assigned: true},
//       {name: 'T.G. Masaryka 34', duration: 60, assigned: true},
//       {name: 'T.G. Masaryka 36', duration: 60, assigned: true},
//       {name: 'Gymnastická hala', duration: 90, assigned: true},
//       {name: 'M.R. Stefánika 49', duration: 60, assigned: true},
//       {name: 'Nábrežná 99', duration: 90, assigned: true},
//       {name: 'Nábrežná 20', duration: 90, assigned: true},
//       {name: 'S.H. Vajanského 70', duration: 60, assigned: true},
//       {name: 'S.H. Vajanského 72', duration: 60, assigned: true},
//       {name: 'Várdayho 13', duration: 30, assigned: true},
//       {name: 'Bitúnková 1', duration: 60, assigned: true},
//       {name: 'Bitúnková 3', duration: 60, assigned: true},
//       {name: 'Bitúnková 5', duration: 60, assigned: true},
//       {name: 'Bitúnková 7', duration: 60, assigned: true},
//       {name: 'Bitúnková 9', duration: 60, assigned: true},
//       {name: 'Bitúnková 11', duration: 60, assigned: true},
//       {name: 'L. Štúra 16B', duration: 60, assigned: true},
//       {name: 'MAGNUM', duration: 90, assigned: true},
//       {name: 'Bajč 197A', duration: 60, assigned: true},
//       {name: 'Bajč 197B', duration: 60, assigned: true},
//       {name: 'Námestie republiky 2', duration: 90, assigned: true},
//       {name: 'Bitúnková 1', duration: 60, assigned: true},
//       {name: 'Bitúnková 3', duration: 60, assigned: true},
//       {name: 'Bitúnková 5', duration: 60, assigned: true},
//       {name: 'Nábrežná 51', duration: 60, assigned: true},
//       {name: 'Gymnastická hala', duration: 90, assigned: true},
//       {name: 'Gogoľová 9', duration: 30, assigned: true},
//       {name: 'Gogoľová 11', duration: 60, assigned: true},
//       {name: 'Gogoľová 17', duration: 60, assigned: true},
//       {name: 'Cyrilometódska 28', duration: 60, assigned: true},
//       {name: 'Cyrilometódska 30', duration: 60, assigned: true},
//       {name: 'Cyrilometódska 32', duration: 60, assigned: true},
//       {name: 'SNP 42', duration: 60, assigned: true},
//       {name: 'Andovská 15', duration: 30, assigned: true},
//       {name: 'Andovská 21', duration: 60, assigned: true},
//       {name: 'Andovská 23', duration: 60, assigned: true},
//       {name: 'Andovská 25A', duration: 30, assigned: true},
//       {name: 'Andovská 25B', duration: 60, assigned: true},
//       {name: 'Andovská 25E', duration: 30, assigned: true},
//       {name: 'Jazdecká 15', duration: 60, assigned: true},
//       {name: 'Jazdecká 17', duration: 60, assigned: true},
//       {name: 'Jazdecká 14', duration: 60, assigned: true},
//       {name: 'Jazdecká 18', duration: 60, assigned: true},
//       {name: 'Komenského 1', duration: 30, assigned: true},
//       {name: 'Komenského 2', duration: 30, assigned: true},
//       {name: 'Bezručová 8', duration: 30, assigned: true},
//       {name: 'Bezručová 10', duration: 30, assigned: true},
//       {name: 'Žerotínová bašta 13', duration: 60, assigned: true},
//       {name: 'Žerotínová bašta 15', duration: 60, assigned: true}
//     ]
//   });
//
//   Seeder.seed('Cleaners init', Cleaners, {
//     data: [
//       {name: 'Lenka B.', salary: 2.7},
//       {name: 'Janka D.', salary: 2.5},
//       {name: 'Katka K.', salary: 2.7},
//       {name: 'Gabika K.', salary: 2.5},
//       {name: 'Nika Č.', salary: 2.5},
//       {name: 'Gabika C.', salary: 2.5}
//     ]
//   });
//
//   var allBuildings = Buildings.find().fetch();
//   allBuildings = _.indexBy(allBuildings, 'name');
//
//   var allCleaners = Cleaners.find().fetch();
//   allCleaners = _.indexBy(allCleaners, 'name');
//
//   var scheduleData = [
//       {day: 1, building: 'Letomostie 7', cleaner: 'Lenka B.'},
//       {day: 1, building: 'Letomostie 11', cleaner: 'Lenka B.'},
//       {day: 1, building: 'Letomostie 13', cleaner: 'Lenka B.'},
//       {day: 1, building: 'Letomostie 15', cleaner: 'Lenka B.'},
//       {day: 1, building: 'Novomestská 2', cleaner: 'Janka D.'},
//       {day: 1, building: 'Novomestská 4', cleaner: 'Janka D.'},
//       {day: 1, building: 'T.G.Masaryka 30', cleaner: 'Janka D.'},
//       {day: 1, building: 'T.G.Masaryka 28', cleaner: 'Janka D.'},
//       {day: 1, building: 'T.G.Masaryka 17', cleaner: 'Janka D.'},
//       {day: 1, building: 'Podzámska 1', cleaner: 'Katka K.'},
//       {day: 1, building: 'Podzámska 7', cleaner: 'Katka K.'},
//       {day: 1, building: 'MAGNUM', cleaner: 'Katka K.'},
//       {day: 1, building: 'T.G. Masaryka 14', cleaner: 'Katka K.'},
//       {day: 1, building: 'T.G. Masaryka 16', cleaner: 'Katka K.'},
//       {day: 1, building: 'T.G. Masaryka 18', cleaner: 'Katka K.'},
//       {day: 1, building: 'SNP. 48', cleaner: 'Gabika K.'},
//       {day: 1, building: 'SNP. 50', cleaner: 'Gabika K.'},
//       {day: 1, building: 'SNP. 52', cleaner: 'Gabika K.'},
//       {day: 1, building: 'SNP. 54', cleaner: 'Gabika K.'},
//       {day: 1, building: 'Gymnastická hala', cleaner: 'Nika Č.'},
//       {day: 1, building: 'ABC klíma', cleaner: 'Nika Č.'},
//       {day: 1, building: 'G. Bethlena 57', cleaner: 'Nika Č.'},
//       {day: 1, building: 'Cyrilometódska 44', cleaner: 'Gabika C.'},
//       {day: 1, building: 'Cyrilometódska 46', cleaner: 'Gabika C.'},
//       {day: 1, building: 'Cyrilometódska 48', cleaner: 'Gabika C.'},
//       {day: 1, building: 'SNP 58', cleaner: 'Gabika C.'},
//       {day: 2, building: 'Šafáriková 26', cleaner: 'Lenka B.'},
//       {day: 2, building: 'Šafáriková 28', cleaner: 'Lenka B.'},
//       {day: 2, building: 'Šafáriková 22', cleaner: 'Lenka B.'},
//       {day: 2, building: 'Šafáriková 20', cleaner: 'Lenka B.'},
//       {day: 2, building: 'Šafáriková 2', cleaner: 'Lenka B.'},
//       {day: 2, building: 'Lastovičia 3', cleaner: 'Lenka B.'},
//       {day: 2, building: 'Lastovičia 1', cleaner: 'Lenka B.'},
//       {day: 2, building: 'Nábrežná 7', cleaner: 'Janka D.'},
//       {day: 2, building: 'Nábrežná 9', cleaner: 'Janka D.'},
//       {day: 2, building: 'Nábrežná 13', cleaner: 'Janka D.'},
//       {day: 2, building: 'Andovská 21', cleaner: 'Janka D.'},
//       {day: 2, building: 'Andovská 23', cleaner: 'Janka D.'},
//       {day: 2, building: 'S.H. Vajanského 37', cleaner: 'Katka K.'},
//       {day: 2, building: 'S.H. Vajanského 39', cleaner: 'Katka K.'},
//       {day: 2, building: 'S.H. Vajanského 41', cleaner: 'Katka K.'},
//       {day: 2, building: 'T. Vansovej 32', cleaner: 'Katka K.'},
//       {day: 2, building: 'T. Vansovej 30', cleaner: 'Katka K.'},
//       {day: 2, building: 'Komárňanska 59', cleaner: 'Gabika K.'},
//       {day: 2, building: 'Dom politických strán', cleaner: 'Gabika K.'},
//       {day: 2, building: 'Komárňanska 29', cleaner: 'Gabika K.'},
//       {day: 2, building: 'Komárňanska 27', cleaner: 'Gabika K.'},
//       {day: 2, building: 'Nábrežná 35', cleaner: 'Gabika C.'},
//       {day: 2, building: 'Nábrežná 37', cleaner: 'Gabika C.'},
//       {day: 2, building: 'Nábrežná 53', cleaner: 'Gabika C.'},
//       {day: 2, building: 'Nábrežná 55', cleaner: 'Gabika C.'},
//       {day: 3, building: 'S.H Vajanského 9', cleaner: 'Lenka B.'},
//       {day: 3, building: 'S.H Vajanského 17', cleaner: 'Lenka B.'},
//       {day: 3, building: 'Šoltésová 9', cleaner: 'Lenka B.'},
//       {day: 3, building: 'J.Krála 20', cleaner: 'Lenka B.'},
//       {day: 3, building: 'J.Krála 22', cleaner: 'Lenka B.'},
//       {day: 3, building: 'T. Vansovej 24', cleaner: 'Janka D.'},
//       {day: 3, building: 'T. Vansovej 22', cleaner: 'Janka D.'},
//       {day: 3, building: 'T. Vansovej 20', cleaner: 'Janka D.'},
//       {day: 3, building: 'T. Vansovej 18', cleaner: 'Janka D.'},
//       {day: 3, building: 'T. Vansovej 16', cleaner: 'Janka D.'},
//       {day: 3, building: 'T. Vansovej 14', cleaner: 'Janka D.'},
//       {day: 3, building: 'Gogoľova 1', cleaner: 'Katka K.'},
//       {day: 3, building: 'Gogoľova 3', cleaner: 'Katka K.'},
//       {day: 3, building: 'Gogoľova 5', cleaner: 'Katka K.'},
//       {day: 3, building: 'Krasková 4', cleaner: 'Katka K.'},
//       {day: 3, building: 'Holého 4', cleaner: 'Katka K.'},
//       {day: 3, building: 'Hlboká 1', cleaner: 'Katka K.'},
//       {day: 3, building: 'Gogoľová 2', cleaner: 'Gabika K.'},
//       {day: 3, building: 'Komárňanska 31', cleaner: 'Gabika K.'},
//       {day: 3, building: 'Ďorocká 3', cleaner: 'Gabika K.'},
//       {day: 3, building: 'Ďorocká 5', cleaner: 'Gabika K.'},
//       {day: 3, building: 'Ďorocká 7', cleaner: 'Gabika K.'},
//       {day: 3, building: 'T.G. Masaryka 32', cleaner: 'Nika Č.'},
//       {day: 3, building: 'T.G. Masaryka 34', cleaner: 'Nika Č.'},
//       {day: 3, building: 'T.G. Masaryka 36', cleaner: 'Nika Č.'},
//       {day: 3, building: 'Gymnastická hala', cleaner: 'Gabika C.'},
//       {day: 3, building: 'M.R. Stefánika 49', cleaner: 'Gabika C.'},
//       {day: 4, building: 'Nábrežná 99', cleaner: 'Lenka B.'},
//       {day: 4, building: 'Nábrežná 20', cleaner: 'Lenka B.'},
//       {day: 4, building: 'S.H. Vajanského 70', cleaner: 'Lenka B.'},
//       {day: 4, building: 'S.H. Vajanského 72', cleaner: 'Lenka B.'},
//       {day: 4, building: 'Várdayho 13', cleaner: 'Lenka B.'},
//       {day: 4, building: 'Bitúnková 1', cleaner: 'Janka D.'},
//       {day: 4, building: 'Bitúnková 3', cleaner: 'Janka D.'},
//       {day: 4, building: 'Bitúnková 5', cleaner: 'Janka D.'},
//       {day: 4, building: 'Bitúnková 7', cleaner: 'Janka D.'},
//       {day: 4, building: 'Bitúnková 9', cleaner: 'Janka D.'},
//       {day: 4, building: 'Bitúnková 11', cleaner: 'Janka D.'},
//       {day: 4, building: 'L. Štúra 16B', cleaner: 'Katka K.'},
//       {day: 4, building: 'MAGNUM', cleaner: 'Katka K.'},
//       {day: 4, building: 'Bajč 197A', cleaner: 'Katka K.'},
//       {day: 4, building: 'Bajč 197B', cleaner: 'Katka K.'},
//       {day: 4, building: 'Námestie republiky 2', cleaner: 'Katka K.'},
//       {day: 4, building: 'Bitúnková 1', cleaner: 'Gabika K.'},
//       {day: 4, building: 'Bitúnková 3', cleaner: 'Gabika K.'},
//       {day: 4, building: 'Bitúnková 5', cleaner: 'Gabika K.'},
//       {day: 4, building: 'Nábrežná 51', cleaner: 'Gabika K.'},
//       {day: 4, building: 'Gymnastická hala', cleaner: 'Gabika C.'},
//       {day: 4, building: 'Gogoľová 9', cleaner: 'Gabika C.'},
//       {day: 4, building: 'Gogoľová 11', cleaner: 'Gabika C.'},
//       {day: 4, building: 'Gogoľová 17', cleaner: 'Gabika C.'},
//       {day: 5, building: 'Cyrilometódska 28', cleaner: 'Lenka B.'},
//       {day: 5, building: 'Cyrilometódska 30', cleaner: 'Lenka B.'},
//       {day: 5, building: 'Cyrilometódska 32', cleaner: 'Lenka B.'},
//       {day: 5, building: 'SNP 42', cleaner: 'Lenka B.'},
//       {day: 5, building: 'Andovská 15', cleaner: 'Janka D.'},
//       {day: 5, building: 'Andovská 21', cleaner: 'Janka D.'},
//       {day: 5, building: 'Andovská 23', cleaner: 'Janka D.'},
//       {day: 5, building: 'Andovská 25A', cleaner: 'Janka D.'},
//       {day: 5, building: 'Andovská 25B', cleaner: 'Janka D.'},
//       {day: 5, building: 'Andovská 25E', cleaner: 'Janka D.'},
//       {day: 5, building: 'Jazdecká 15', cleaner: 'Katka K.'},
//       {day: 5, building: 'Jazdecká 17', cleaner: 'Katka K.'},
//       {day: 5, building: 'Jazdecká 14', cleaner: 'Katka K.'},
//       {day: 5, building: 'Jazdecká 18', cleaner: 'Katka K.'},
//       {day: 5, building: 'Komenského 1', cleaner: 'Katka K.'},
//       {day: 5, building: 'Komenského 2', cleaner: 'Katka K.'},
//       {day: 5, building: 'Bezručová 8', cleaner: 'Katka K.'},
//       {day: 5, building: 'Bezručová 10', cleaner: 'Katka K.'},
//       {day: 5, building: 'Žerotínová bašta 13', cleaner: 'Gabika K.'},
//       {day: 5, building: 'Žerotínová bašta 15', cleaner: 'Gabika K.'}
//   ];
//
//   // var scheduleData1 = [];
//   // _.each(scheduleData, function(item, index) {
//
//   //     if (!allBuildings[item.building]) log('Missing building:', item.building)
//   //     if (!allCleaners[item.cleaner]) log('Missing cleaner:-' + item.cleaner + '-')
//   //     scheduleData1.push({
//   //           building_id: allBuildings[item.building]._id,
//   //           cleaner_id: allCleaners[item.cleaner]._id,
//   //           createdAt: new Date(),
//   //           day: item.day
//   //     })
//   // });
//
//   // Seeder.seed('Schedules init', Schedules, {
//   //   data: scheduleData1
//   // });
//
//   // createJobs();
//
// });
